config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :posts

  root 'welcome#index'

  namespace :admin do
    resources :users
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  validates :name, length: {minimum: 4, allow_nil: true, allow_blank: true, message: "El nombre tiene que tener más de cuatro letras o bien ser dejado en blanco."}
  validates :last_name, length: {maximum: 60}

  validates :email, format: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :validacion
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def validacion
  end

  # GET /users
  # GET /users.json
  def index
    @cnt   = User.count
    if ['name', 'last_name', 'age', 'email'].include?(params[:order])
      @users = User.order(params[:order])
    else
      @users = User.order(:name)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'Se creo un usuario exitosamente.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Usuario actualizado exitosamente.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Usuario fue exitosamente eliminado.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :last_name, :age, :email, :notes)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || posts_path
  end

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :last_name, :email, :password, :current_password) }
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :create, :edit, :update]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def set_users
      @users = User.order(:last_name, :name).all
      @categories = Category.order(:name).all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :subtitle, :content, :user_id, category_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_name(user)
    "#{user.last_name}, #{user.name}"
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def user_options(users)
    users.map {|user| [full_name(user), user.id] }
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar(email)
    hash = Digest::MD5.hexdigest(email)
    image_tag "http://www.gravatar.com/avatar/" + hash
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> error(es) Prohibió que este usuario sea salvado:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editando usuario</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @user %> |
<%= link_to 'Atras', users_path %>

app/views/admin/users/index.html.erb
<h1><%= image_tag "http://i1142.photobucket.com/albums/n617/Conficker_EJ/user-group-icon.png", width: '50px' %>

Listado de Usuarios (<%= @cnt %>)</h1>

<%= Date.today %>
<br>
<%= link_to "Noticias", "http://www.lagaceta.com.ar", target: '_blank' %>
<br>
<table>
  <thead>
    <tr>
      <th>Foto</th>
      <th><%= link_to "Nombre", admin_users_path(order: 'name') %></th>
      <th><%= link_to "Apellido", admin_users_path(order: 'last_name') %></th>
      <th><%= link_to "Edad", admin_users_path(order: 'age') %></th>
      <th><%= link_to "Email", admin_users_path(order: 'email') %></th>
      <th>Artículos</th>
      <th>Anotaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= gravatar(user.email) %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.age %></td>
        <td><%= user.email %></td>
        <td><%= user.posts.count %></td>
        <td><%= user.notes %></td>
        <td><%= link_to 'Ver', admin_users_path(user) %></td>
        <td><%= link_to 'Editar', edit_admin_user_path(user) %></td>
        <td><%= link_to 'Eliminar', admin_users_path(user), {method: :delete, data: { confirm: 'Estás seguro de eliminar este usuario?' } } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>Nuevo Usuario</h1>

<%= render 'form' %>

<%= link_to 'Atras', users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Anotaciones:</strong>
  <%= @user.notes %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Volver', users_path %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_url %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aplicacion Rails Hola Mundo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>  
  <% if user_signed_in? %>
    <p>Hola: <%= current_user.name %></p>
  <% end %>
  <%= link_to "Inicio",    root_path %>
  <%= link_to "Artículos", posts_path %>
  <%= link_to "Usuarios",  admin_users_path %>
  <%= link_to "Categorias",  categories_path %>
  <% if user_signed_in? %>
    <%= link_to "Editar Perfil", edit_user_registration_path %>
    <%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Ingresar", new_user_session_path %>
  <% end %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</header>

  <%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Titulo" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle, "Subtitulo" %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :content, "Contenido" %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id, "Autor" %><br>
    <%= f.select :user_id, user_options(@users) %>
  </div>
  <div class="field">
    <%= f.label :categories, "Categorias" %><br>
    <% for category in @categories do %>
      <%= check_box_tag "post[category_ids][]", category.id, @post.categories.member?(category) %>
      <%= category.name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listado de Artículos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Subtitulo</th>
      <th>Contenido</th>
      <th>Autor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.subtitle %></td>
        <td><%= post.content %></td>
        <td><%= post.user.name %></td>
        <td><%= link_to 'Ver', post %></td>
        <td><%= link_to 'Editar', edit_post_path(post) %></td>
        <td><%= link_to 'Eliminar', post, method: :delete, data: { confirm: 'Está seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Articulo', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Subtitulo:</strong>
  <%= @post.subtitle %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= full_name @post.user %>
</p>

<p>
  <strong>Categorias:</strong>
  <%= @post.categories.map{|category| category.name }.join(', ') %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= image_tag "http://i1142.photobucket.com/albums/n617/Conficker_EJ/user-group-icon.png", width: '50px' %>

Listado de Usuarios (<%= @cnt %>)</h1>

<%= Date.today %>
<br>
<%= link_to "Noticias", "http://www.lagaceta.com.ar", target: '_blank' %>
<br>
<table>
  <thead>
    <tr>
      <th>Foto</th>
      <th><%= link_to "Nombre", users_path(order: 'name') %></th>
      <th><%= link_to "Apellido", users_path(order: 'last_name') %></th>
      <th><%= link_to "Edad", users_path(order: 'age') %></th>
      <th><%= link_to "Email", users_path(order: 'email') %></th>
      <th>Artículos</th>
      <th>Anotaciones</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= gravatar(user.email) %></td>
        <td><%= user.name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.age %></td>
        <td><%= user.email %></td>
        <td><%= user.posts.count %></td>
        <td><%= user.notes %></td>
        <td><%= link_to 'Ver', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Eliminar', user, {method: :delete, data: { confirm: 'Estás seguro de eliminar este usuario?' } } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Usuario', new_user_path %>

app/views/welcome/index.html.erb
<h1>Hola Mundo!</h1>
<p>Esta es la primera accion creada en el controller.</p>